### ISSUE TITLE
[auto_animated] Is there a way to avoid animation when out of the website area?

### ISSUE THREAD

**Issue by mrigankdoshy** [ScerIO/packages.flutter#303] opened 2022-05-24 23:14 UTC
## Description:

I'm building a personal portfolio website that uses the `auto_animated` package to animate widgets when they become visible. 

More specifically, I'm using it to animate widgets with delay (top to bottom) as I scroll through the website:

https://user-images.githubusercontent.com/32623983/170142619-cdabaf89-c807-445e-bbbb-fe4713606205.mov

I'd like this to happen only once - that is when the website is first loaded. 

The issue I'm facing is that whenever I move out of the website area (to use the toolbar, switch tabs or resize the window), the animations reoccur in random/weird order as if it's rebuilding. In the video below you'll see that when I mouse my mouse to the toolbar area or when I resize the browser, the animations reoccur.

https://user-images.githubusercontent.com/32623983/170143626-4e130339-7f4e-4b4d-9cc6-ebdbabdaded6.mov

Is there a way to only animate the first time the app builds and ensure that it does not animate again when trying to resize the window or do pretty much anything outside the website area?

## Code:

<details>
  <summary>Click for usage of AnimateIfVisibleWrapper</summary>

---

`home.dart` contains: 

```dart
  Widget build(BuildContext context) {
    return Scaffold(
      body: AnimateIfVisibleWrapper(
        child: CustomScrollView(
          physics: const BouncingScrollPhysics(),
          slivers: [
            SliverAppBar(
              floating: true,
              flexibleSpace: _appBar(),
              backgroundColor: AppColors.backgroundBlue,
              expandedHeight: 90,
            ),
            SliverToBoxAdapter(
              child: ResponsiveWidget(
                largeScreen: _buildLargeScreen(context),
                mediumScreen: _buildMediumScreen(context),
                smallScreen: _buildSmallScreen(context),
              ),
            ),
          ],
        ),
      ),
    );
  }
```
</details>

<details>
  <summary>Click for usage of AnimateIfVisible</summary>

---

I have a resuable wrapper for the `AnimateIfVisible` called `SlideAnimation`:

```dart
class SlideAnimation extends StatelessWidget {
  final UniqueKey animationKey;
  final bool slideDown;
  final Duration duration;
  final Duration delay;
  final Widget child;

  const SlideAnimation({
    Key? key,
    required this.animationKey,
    required this.child,
    this.slideDown = false,
    this.delay = const Duration(milliseconds: 0),
    this.duration = const Duration(milliseconds: 300),
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AnimateIfVisible(
      key: animationKey,
      duration: duration,
      delay: delay,
      builder: (
        BuildContext context,
        Animation<double> animation,
      ) =>
          FadeTransition(
        opacity: Tween<double>(
          begin: 0,
          end: 1,
        ).animate(CurvedAnimation(parent: animation, curve: Curves.easeOut)),
        child: SlideTransition(
          position: Tween<Offset>(
            begin: slideDown ? const Offset(0, -0.8) : const Offset(0, 0.8),
            end: Offset.zero,
          ).animate(animation),
          child: child,
        ),
      ),
    );
  }
}
```
</details>

<details>
  <summary>Click for usage of SlideAnimation</summary>

---

I then use this to animate each widget. For example, I use it to animate each menu button in the app bar (`_appBar()` called from `home.dart` as seen in the first exapandable above):

```dart
  Widget _appBar() {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 24.0, horizontal: 72.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            SlideAnimation(
              animationKey: UniqueKey(),
              slideDown: true,
              child: MenuButtton(
                dataKey: dataKeys[0],
                buttonNumber: ButtonData.buttonNumber1,
                buttonTitle: ButtonData.button1Title,
              ),
            ),
            const SizedBox(width: 8.0),
            SlideAnimation(
              animationKey: UniqueKey(),
              slideDown: true,
              delay: const Duration(milliseconds: 50),
              child: MenuButtton(
                dataKey: dataKeys[1],
                buttonNumber: ButtonData.buttonNumber2,
                buttonTitle: ButtonData.button2Title,
              ),
            ),
            ...
            ),
          ],
        ),
      ),
    );
  }
```
</details>

---

This might not be related to the package itself and could be a flutter question, but I'd truly appreciate any insight! If you need any clarification or have any questions, please feel free to reach out!

P.S. I'm sorry I didn't use a template for this issue as it's a question and not a bug / feature request

Thank you :)

**Comment by SergeShkurko** [comment] 2022-07-19 00:47
@mrigankdoshy hello
did you find out what the problem is?

`AnimateIfVisible` widget includes reAnimate property and he's off by default:
https://github.com/ScerIO/packages.flutter/blob/a6638936fc16ec2712ee0659c13ce502ed37395f/packages/auto_animated/lib/src/animate_if_visible.dart#L16-L23

Your problem was not so much replaying the animation as rebuilding the element tree
you are passing unique keys to the SlideAnimation widget.
And you initialize them inside the build method build()->_appBar()

Every time setState is called or like in your case exiting the site arena
flutter sees new keys every time and considers that these are new elements - redrawing them and playing the animation in first once (not re-animating)

<img width="639" alt="image" src="https://user-images.githubusercontent.com/18213789/179639516-806ccd91-b348-4e6a-81c8-a0d19c8d4efc.png">

The solution for you would be, for example, one of:
  - Using Key("key id")
  - initialization and pre-recording to UniqueKey() variables
  
  ```dart
    Widget _appBar() {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 24.0, horizontal: 72.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            SlideAnimation(
              animationKey: Key("button1_key"),
              slideDown: true,
              child: MenuButtton(
                dataKey: dataKeys[0],
                buttonNumber: ButtonData.buttonNumber1,
                buttonTitle: ButtonData.button1Title,
              ),
            ),
            const SizedBox(width: 8.0),
            SlideAnimation(
              animationKey: Key("button1_key"),
              slideDown: true,
              delay: const Duration(milliseconds: 50),
              child: MenuButtton(
                dataKey: dataKeys[1],
                buttonNumber: ButtonData.buttonNumber2,
                buttonTitle: ButtonData.button2Title,
              ),
            ),
            ...
            ),
          ],
        ),
      ),
    );
  }
  ```
  
While I close the issue
Let me know if the solution did not help - I will reopen

**Closed by SergeShkurko** 2022-07-19 00:47 UTC
